# Generated by Django 4.2.11 on 2025-02-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
